<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1740575356923' stop='1740575396681'>
    <name>SampleForm login test</name>
    <title>SampleForm login test</title>
    <test-cases>
        <test-case start='1740575356923' status='failed' stop='1740575396680'>
            <name>login as SampleForm</name>
            <title>login as SampleForm</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='fa96142c-7f25-41f3-a892-226dca8e2697-attachment.png' type='image/png' size='35508'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\SHVYSYAR\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at listOnTimeout (node:internal/timers:614:17)
                    at processTimers (node:internal/timers:549:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>